const restaurantSeed = [
	{
		business_status: 'OPERATIONAL',
		geometry: { location: [Object], viewport: [Object] },
		icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
		icon_background_color: '#FF9E67',
		icon_mask_base_uri: 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
		name: '拿靠早午餐｜忠孝店｜林口早午餐｜團體訂購｜外帶美食',
		opening_hours: { open_now: false },
		photos: [[Object]],
		place_id: 'ChIJHaW1GJSnQjQRQLrlRoFQN2Y',
		plus_code: { compound_code: '39F7+5J 台灣新北市林口區', global_code: '7QQ339F7+5J' },
		rating: 4.9,
		reference: 'ChIJHaW1GJSnQjQRQLrlRoFQN2Y',
		scope: 'GOOGLE',
		types: ['restaurant', 'food', 'point_of_interest', 'establishment'],
		user_ratings_total: 133,
		vicinity: '林口區忠孝一路9號',
		url: 'https://maps.google.com/?cid=7365444231758199360',
	},
	{
		business_status: 'OPERATIONAL',
		geometry: { location: [Object], viewport: [Object] },
		icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/cafe-71.png',
		icon_background_color: '#FF9E67',
		icon_mask_base_uri: 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/cafe_pinlet',
		name: 'HOMI CAFE & SPACE',
		opening_hours: { open_now: true },
		photos: [[Object]],
		place_id: 'ChIJsw3xizinQjQRm2s_Z7PW85Q',
		plus_code: { compound_code: '39F7+FW 台灣新北市林口區', global_code: '7QQ339F7+FW' },
		rating: 4.8,
		reference: 'ChIJsw3xizinQjQRm2s_Z7PW85Q',
		scope: 'GOOGLE',
		types: ['cafe', 'restaurant', 'food', 'point_of_interest', 'establishment'],
		user_ratings_total: 42,
		vicinity: '林口區南勢街23號ㄧ樓',
		url: 'https://maps.google.com/?cid=10733158402973723547',
	},
	{
		business_status: 'OPERATIONAL',
		geometry: { location: [Object], viewport: [Object] },
		icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
		icon_background_color: '#FF9E67',
		icon_mask_base_uri: 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
		name: 'mmmMUNCH好好咀嚼(未來城後方)',
		opening_hours: { open_now: true },
		photos: [[Object]],
		place_id: 'ChIJc41hIW6nQjQROC8MY_GkFIk',
		plus_code: { compound_code: '39C8+P3 台灣新北市林口區', global_code: '7QQ339C8+P3' },
		rating: 4.7,
		reference: 'ChIJc41hIW6nQjQROC8MY_GkFIk',
		scope: 'GOOGLE',
		types: ['restaurant', 'food', 'point_of_interest', 'establishment'],
		user_ratings_total: 76,
		vicinity: '未來城後方, No. 374-3號, 文化三路一段, 林口區',
		url: 'https://maps.google.com/?cid=9877701239386156856',
	},
	{
		business_status: 'OPERATIONAL',
		geometry: { location: [Object], viewport: [Object] },
		icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
		icon_background_color: '#FF9E67',
		icon_mask_base_uri: 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
		name: '莊家班麻油雞-林口文三店',
		opening_hours: { open_now: true },
		photos: [[Object]],
		place_id: 'ChIJzfOiPyinQjQRcBL2_cv2ORA',
		plus_code: { compound_code: '39C7+VJ 台灣新北市林口區', global_code: '7QQ339C7+VJ' },
		rating: 4.7,
		reference: 'ChIJzfOiPyinQjQRcBL2_cv2ORA',
		scope: 'GOOGLE',
		types: ['restaurant', 'food', 'point_of_interest', 'establishment'],
		user_ratings_total: 621,
		vicinity: '林口區文化三路一段313號',
		url: 'https://maps.google.com/?cid=1169236934278910576',
	},
	{
		business_status: 'OPERATIONAL',
		geometry: { location: [Object], viewport: [Object] },
		icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
		icon_background_color: '#FF9E67',
		icon_mask_base_uri: 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
		name: '豆桑全豆豆漿',
		opening_hours: { open_now: true },
		photos: [[Object]],
		place_id: 'ChIJT__sszKnQjQR50kMwSlgBro',
		plus_code: { compound_code: '39F7+FW 台灣新北市林口區', global_code: '7QQ339F7+FW' },
		rating: 4.7,
		reference: 'ChIJT__sszKnQjQR50kMwSlgBro',
		scope: 'GOOGLE',
		types: ['restaurant', 'food', 'point_of_interest', 'establishment'],
		user_ratings_total: 56,
		vicinity: '林口區南勢街21-1號',
		url: 'https://maps.google.com/?cid=13404507073363593703',
	},
	{
		business_status: 'OPERATIONAL',
		geometry: { location: [Object], viewport: [Object] },
		icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
		icon_background_color: '#FF9E67',
		icon_mask_base_uri: 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
		name: 'Eat enjoy意享美式廚房林口三井店 外帶美食 外送美食 林口三井美食 千層蛋糕 美式餐廳 寵物友善',
		opening_hours: { open_now: true },
		photos: [[Object]],
		place_id: 'ChIJT-Z4-yenQjQRwpZVfPqNvZo',
		plus_code: { compound_code: '39F8+29 台灣新北市林口區', global_code: '7QQ339F8+29' },
		price_level: 2,
		rating: 4.6,
		reference: 'ChIJT-Z4-yenQjQRwpZVfPqNvZo',
		scope: 'GOOGLE',
		types: ['restaurant', 'food', 'point_of_interest', 'store', 'establishment'],
		user_ratings_total: 3271,
		vicinity: '林口區文化三路一段390-1號',
		url: 'https://maps.google.com/?cid=11150224359406540482',
	},
	{
		business_status: 'OPERATIONAL',
		geometry: { location: [Object], viewport: [Object] },
		icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
		icon_background_color: '#FF9E67',
		icon_mask_base_uri: 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
		name: '心伝的家',
		opening_hours: { open_now: false },
		photos: [[Object]],
		place_id: 'ChIJKYWJHNmmQjQRoNtmS150OSg',
		plus_code: { compound_code: '39F8+5C 台灣新北市林口區', global_code: '7QQ339F8+5C' },
		price_level: 2,
		rating: 4.4,
		reference: 'ChIJKYWJHNmmQjQRoNtmS150OSg',
		scope: 'GOOGLE',
		types: ['restaurant', 'food', 'point_of_interest', 'establishment'],
		user_ratings_total: 202,
		vicinity: '林口區文化三路一段394巷6號',
		url: 'https://maps.google.com/?cid=2898475783530404768',
	},
	{
		business_status: 'OPERATIONAL',
		geometry: { location: [Object], viewport: [Object] },
		icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
		icon_background_color: '#FF9E67',
		icon_mask_base_uri: 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
		name: '食之有情 : 親子餐廳-林口義式餐廳|早午餐餐廳|必吃美食餐廳|熱門餐廳|親子餐廳|寵物友善餐廳',
		opening_hours: { open_now: true },
		photos: [[Object]],
		place_id: 'ChIJX6DbaSinQjQRevXMxrhScRQ',
		plus_code: { compound_code: '39C7+JM 台灣新北市林口區', global_code: '7QQ339C7+JM' },
		price_level: 2,
		rating: 4.3,
		reference: 'ChIJX6DbaSinQjQRevXMxrhScRQ',
		scope: 'GOOGLE',
		types: ['restaurant', 'food', 'point_of_interest', 'establishment'],
		user_ratings_total: 362,
		vicinity: '林口區文化三路一段358-2號',
		url: 'https://maps.google.com/?cid=1473049506689643898',
	},
	{
		business_status: 'OPERATIONAL',
		geometry: { location: [Object], viewport: [Object] },
		icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
		icon_background_color: '#FF9E67',
		icon_mask_base_uri: 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
		name: '川井棧創意料理館',
		opening_hours: { open_now: false },
		photos: [[Object]],
		place_id: 'ChIJn-VJACinQjQROf1f2Ad8lkc',
		plus_code: { compound_code: '39C8+V6 台灣新北市林口區', global_code: '7QQ339C8+V6' },
		price_level: 2,
		rating: 4.2,
		reference: 'ChIJn-VJACinQjQROf1f2Ad8lkc',
		scope: 'GOOGLE',
		types: ['restaurant', 'food', 'point_of_interest', 'establishment'],
		user_ratings_total: 505,
		vicinity: '林口區文化三路一段384-1號',
		url: 'https://maps.google.com/?cid=5158446796336266553',
	},
	{
		business_status: 'OPERATIONAL',
		geometry: { location: [Object], viewport: [Object] },
		icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
		icon_background_color: '#FF9E67',
		icon_mask_base_uri: 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
		name: '拿靠早午餐',
		opening_hours: { open_now: false },
		photos: [[Object]],
		place_id: 'ChIJv6woayinQjQRi0p5CLbdtME',
		plus_code: { compound_code: '39C7+QQ 台灣新北市林口區', global_code: '7QQ339C7+QQ' },
		price_level: 2,
		rating: 4.1,
		reference: 'ChIJv6woayinQjQRi0p5CLbdtME',
		scope: 'GOOGLE',
		types: ['restaurant', 'food', 'point_of_interest', 'establishment'],
		user_ratings_total: 1113,
		vicinity: '林口區文化三路一段366號',
		url: 'https://maps.google.com/?cid=13958024919023962763',
	},
	{
		business_status: 'OPERATIONAL',
		geometry: { location: [Object], viewport: [Object] },
		icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
		icon_background_color: '#FF9E67',
		icon_mask_base_uri: 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
		name: '張記海南雞飯',
		opening_hours: { open_now: true },
		photos: [[Object]],
		place_id: 'ChIJrQHY3MqrQjQRwfvq6hX4sL4',
		plus_code: { compound_code: '39C7+CW 台灣新北市林口區', global_code: '7QQ339C7+CW' },
		rating: 4.1,
		reference: 'ChIJrQHY3MqrQjQRwfvq6hX4sL4',
		scope: 'GOOGLE',
		types: ['restaurant', 'food', 'point_of_interest', 'establishment'],
		user_ratings_total: 325,
		vicinity: '林口區文化三路一段356號2F',
		url: 'https://maps.google.com/?cid=13740755236126653377',
	},
	{
		business_status: 'OPERATIONAL',
		geometry: { location: [Object], viewport: [Object] },
		icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
		icon_background_color: '#FF9E67',
		icon_mask_base_uri: 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
		name: '品嚐悅-林口特色便當店|外送便當店|辦公室外送美食|推薦便當|必吃便當|便當店推薦',
		opening_hours: { open_now: false },
		photos: [[Object]],
		place_id: 'ChIJW6EMYPqnQjQRSJUdC5r_Hk8',
		plus_code: { compound_code: '39F7+2R 台灣新北市林口區', global_code: '7QQ339F7+2R' },
		price_level: 2,
		rating: 4,
		reference: 'ChIJW6EMYPqnQjQRSJUdC5r_Hk8',
		scope: 'GOOGLE',
		types: ['restaurant', 'food', 'point_of_interest', 'establishment'],
		user_ratings_total: 820,
		vicinity: '林口區文化三路一段333號',
		url: 'https://maps.google.com/?cid=5701275215374161224',
	},
	{
		business_status: 'OPERATIONAL',
		geometry: { location: [Object], viewport: [Object] },
		icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
		icon_background_color: '#FF9E67',
		icon_mask_base_uri: 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
		name: '斑鳩的窩 (林口店)',
		opening_hours: { open_now: false },
		photos: [[Object]],
		place_id: 'ChIJda28RSinQjQRoQQBztSDwAY',
		plus_code: { compound_code: '39C7+RH 台灣新北市林口區', global_code: '7QQ339C7+RH' },
		price_level: 2,
		rating: 4,
		reference: 'ChIJda28RSinQjQRoQQBztSDwAY',
		scope: 'GOOGLE',
		types: ['restaurant', 'food', 'point_of_interest', 'establishment'],
		user_ratings_total: 921,
		vicinity: '林口區文化三路一段309號',
		url: 'https://maps.google.com/?cid=486533709768492193',
	},
	{
		business_status: 'OPERATIONAL',
		geometry: { location: [Object], viewport: [Object] },
		icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
		icon_background_color: '#FF9E67',
		icon_mask_base_uri: 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
		name: '福豆FOODOOR🍔（三井林口店）｜桌菜｜便當｜聚餐',
		opening_hours: { open_now: false },
		photos: [[Object]],
		place_id: 'ChIJNwtY-aGnQjQRu3gTGfMqG4E',
		plus_code: { compound_code: '39C7+RG 台灣新北市林口區', global_code: '7QQ339C7+RG' },
		price_level: 2,
		rating: 4,
		reference: 'ChIJNwtY-aGnQjQRu3gTGfMqG4E',
		scope: 'GOOGLE',
		types: ['restaurant', 'food', 'point_of_interest', 'establishment'],
		user_ratings_total: 429,
		vicinity: '林口區文化三路一段303號',
		url: 'https://maps.google.com/?cid=9303076678850017467',
	},
	{
		business_status: 'OPERATIONAL',
		geometry: { location: [Object], viewport: [Object] },
		icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
		icon_background_color: '#FF9E67',
		icon_mask_base_uri: 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
		name: '林口老眷村牛肉麵',
		opening_hours: { open_now: false },
		photos: [[Object]],
		place_id: 'ChIJvaGsGiinQjQRdpHaU-q7-BE',
		plus_code: { compound_code: '39C7+GQ 台灣新北市林口區', global_code: '7QQ339C7+GQ' },
		price_level: 2,
		rating: 4,
		reference: 'ChIJvaGsGiinQjQRdpHaU-q7-BE',
		scope: 'GOOGLE',
		types: [
			'meal_delivery',
			'meal_takeaway',
			'restaurant',
			'food',
			'point_of_interest',
			'establishment',
		],
		user_ratings_total: 467,
		vicinity: '林口區文化三路一段370號',
		url: 'https://maps.google.com/?cid=1294991507972591990',
	},
	{
		business_status: 'OPERATIONAL',
		geometry: { location: [Object], viewport: [Object] },
		icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
		icon_background_color: '#FF9E67',
		icon_mask_base_uri: 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
		name: '金仙魯肉飯（林口三井店）35年老字號魯肉飯',
		opening_hours: { open_now: false },
		photos: [[Object]],
		place_id: 'ChIJK6unJa-nQjQR5KXS7ign9XM',
		plus_code: { compound_code: '39C7+VJ 台灣新北市林口區', global_code: '7QQ339C7+VJ' },
		price_level: 1,
		rating: 3.9,
		reference: 'ChIJK6unJa-nQjQR5KXS7ign9XM',
		scope: 'GOOGLE',
		types: ['restaurant', 'food', 'point_of_interest', 'establishment'],
		user_ratings_total: 666,
		vicinity: '林口區文化三路一段317號',
		url: 'https://maps.google.com/?cid=8355627740414780900',
	},
	{
		business_status: 'OPERATIONAL',
		geometry: { location: [Object], viewport: [Object] },
		icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
		icon_background_color: '#FF9E67',
		icon_mask_base_uri: 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
		name: '玉女號滷肉飯',
		opening_hours: { open_now: false },
		photos: [[Object]],
		place_id: 'ChIJL5cYIiinQjQRNGKAaakV87E',
		plus_code: { compound_code: '39F7+7M 台灣新北市林口區', global_code: '7QQ339F7+7M' },
		price_level: 2,
		rating: 3.9,
		reference: 'ChIJL5cYIiinQjQRNGKAaakV87E',
		scope: 'GOOGLE',
		types: ['restaurant', 'food', 'point_of_interest', 'establishment'],
		user_ratings_total: 746,
		vicinity: '林口區忠孝一路22號',
		url: 'https://maps.google.com/?cid=12822616381417611828',
	},
	{
		business_status: 'OPERATIONAL',
		geometry: { location: [Object], viewport: [Object] },
		icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
		icon_background_color: '#FF9E67',
		icon_mask_base_uri: 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
		name: '炸鷄大獅林口三井店',
		opening_hours: { open_now: true },
		photos: [[Object]],
		place_id: 'ChIJmSWzzSenQjQRuvpNZj8m0QU',
		plus_code: { compound_code: '39C8+G4 台灣新北市林口區', global_code: '7QQ339C8+G4' },
		rating: 3.8,
		reference: 'ChIJmSWzzSenQjQRuvpNZj8m0QU',
		scope: 'GOOGLE',
		types: ['restaurant', 'food', 'point_of_interest', 'establishment'],
		user_ratings_total: 316,
		vicinity: '林口區文化三路一段356號',
		url: 'https://maps.google.com/?cid=419158294063348410',
	},
	{
		business_status: 'OPERATIONAL',
		geometry: { location: [Object], viewport: [Object] },
		icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
		icon_background_color: '#FF9E67',
		icon_mask_base_uri: 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
		name: '點水樓(林口店)',
		opening_hours: { open_now: true },
		photos: [[Object]],
		place_id: 'ChIJ3UVH1SenQjQRq_vPd3Ftvvw',
		plus_code: { compound_code: '39C8+G4 台灣新北市林口區', global_code: '7QQ339C8+G4' },
		price_level: 3,
		rating: 3.8,
		reference: 'ChIJ3UVH1SenQjQRq_vPd3Ftvvw',
		scope: 'GOOGLE',
		types: ['restaurant', 'food', 'point_of_interest', 'establishment'],
		user_ratings_total: 1699,
		vicinity: '林口區文化三路一段356號',
		url: 'https://maps.google.com/?cid=18212114277241715627',
	},
	{
		business_status: 'OPERATIONAL',
		geometry: { location: [Object], viewport: [Object] },
		icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
		icon_background_color: '#FF9E67',
		icon_mask_base_uri: 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
		name: '韓國一隻雞',
		opening_hours: { open_now: true },
		photos: [[Object]],
		place_id: 'ChIJ13LgWCinQjQRw4MrJH5zG6Q',
		plus_code: { compound_code: '39C8+G4 台灣新北市林口區', global_code: '7QQ339C8+G4' },
		rating: 3.7,
		reference: 'ChIJ13LgWCinQjQRw4MrJH5zG6Q',
		scope: 'GOOGLE',
		types: ['restaurant', 'food', 'point_of_interest', 'establishment'],
		user_ratings_total: 1076,
		vicinity: '林口區文化三路一段356號',
		url: 'https://maps.google.com/?cid=11825172232201274307',
	},
];

module.exports = restaurantSeed;
